name: screen_builder
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  easy_mask: ^1.1.5
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

