name: screen_builder
description: A server ui driven flutter engine package.
version: 1.0.0-beta
author: Mobile Chapter - Youse Seguros
homepage: https://github.com/youse-seguradora/mob-flutter-screen-builder
repository: https://github.com/youse-seguradora/mob-flutter-screen-builder
publish_to: https://pub.dev/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: 4.1.1
  test: any
  bloc_test: ^7.0.0

flutter:

