name: screen_builder
description: A server ui driven flutter engine package.
version: 1.0.0-beta
author: Mobile Chapter - Youse Seguros
homepage: https://github.com/youse-seguradora/mob-flutter-screen-builder
repository: https://github.com/youse-seguradora/mob-flutter-screen-builder

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

